name: '[Deprecated] LLM Prompt Testing (LangChain)'

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683    

    - name: 'set up git LFS'
      run: git lfs install

    - name: 'set up Python'
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'

    - name: 'set up Microsoft Phi-3 Mini 4k LLM from HuggingFace'
      run: |
        pip install huggingface-hub[cli]
        huggingface-cli download microsoft/Phi-3-mini-4k-instruct-onnx --include cpu_and_mobile/cpu-int4-rtn-block-32-acc-level-4/* --local-dir ${{ github.workspace }}/tests/llm

    - name: 'test'
      run: |
        pip install langchain_community
        pip install langchain_text_splitters
        pip install langchain_huggingface 
        pip install transformers
        pip install accelerate
        pip install optimum[exporters,onnxruntime]
        pip install faiss-cpu
        pip install hf_xet
        
        python -m tests.llm.llm_rag
        
