name: '#3 (21-40)'
on:
  workflow_dispatch:
  # schedule:
  # - cron: '20 5-23/8 * * *'


jobs:
  test-prompts-21-40:
    uses: ./.github/workflows/test_03.base.yml
    with:
      batch_offset: 20
      range_name: "21-40"
      batch_size: 2