name: '#3 (81-100)'
on:
  workflow_dispatch:
  # schedule:
  # - cron: '20 6-23/8 * * *'


jobs:
  test-prompts-81-100:
    uses: ./.github/workflows/test_03.base.yml
    with:
      batch_offset: 80
      range_name: "81-100"
      batch_size: 2