name: '#4 (21-40)'
on:
  workflow_dispatch:
  # schedule:
  # - cron: '20 0-23/8 * * *'
  # - cron: '0 7-23/8 * * *'


jobs:
  test-prompts-21-40:
    uses: ./.github/workflows/test_04.base.yml
    with:
      batch_offset: 20
      range_name: "21-40"
      batch_size: 2