name: '#4 (81-100)'
on:
  workflow_dispatch:
  # schedule:
  # - cron: '20 1-23/8 * * *'
  # - cron: '0 8-23/8 * * *'

jobs:
  test-prompts-81-100:
    uses: ./.github/workflows/test_04.base.yml
    with:
      batch_offset: 80
      range_name: "81-100"
      batch_size: 2