name: '#1 (41-60)'
on:
  workflow_dispatch:
  # schedule:
  # - cron: '20 2-23/8 * * *'


jobs:
  test-prompts-41-60:
    uses: ./.github/workflows/test_01.base.yml
    with:
      batch_offset: 40
      range_name: "41-60"
      batch_size: 2
