name: '#4 (61-80)'
on:
  workflow_dispatch:
  # schedule:
  # - cron: '0 1-23/8 * * *'
  # - cron: '40 7-23/8 * * *'

jobs:
  test-prompts-61-80:
    uses: ./.github/workflows/test_04.base.yml
    with:
      batch_offset: 60
      range_name: "61-80"
      batch_size: 2