name: '#3 (1-20)'
on:
  workflow_dispatch:
  # schedule:
  # - cron: '0 5-23/8 * * *'


jobs:
  test-prompts-1-20:
    uses: ./.github/workflows/test_03.base.yml
    with:
      batch_offset: 0
      range_name: "1-20"
      batch_size: 2